# Generated by Django 2.0.2 on 2018-02-17 21:22

from django.db import migrations, models
import text.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10, validators=[text.models.validate_phone])),
                ('message', models.CharField(max_length=153)),
                ('response', models.CharField(max_length=153)),
            ],
        ),
    ]
