# Generated by Django 2.0.2 on 2018-02-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_auto_20180217_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='response',
            field=models.CharField(blank=True, max_length=153),
        ),
    ]
